### ISSUE TITLE
Animations in action? Shaped buttons, dragable graphics and Phoenix/wxWidgets?

### ISSUE THREAD

**Issue by jrie** [Metallicow/MCOW#1]
Hello,

I've got several questions regarding your library, which are not yet quite clear to me.

Firstly, is it possible to see or get a list of animations possible with this library/extension and with what kind of controls those can be used with? Perhaps as animated gifs or webm or similar showing them in action? Would be great to get a overview of this feature(s).

Secondly, the shaped and styleable buttons looking very promising and could be of good use! Can those be positioned dynamically/freely in a window space or are there any constrains on that? (I haven't been using wxWidgets itself for quite some time...)

Another question, is there any chance or way that there might be a addition to create dragable graphics, for example for touch devices? Perhaps managed in layers with the combination of shaped buttons? I would have a use case for that and likely would ditch some other "library" for that, providing it can resemble what has been done in the past using other software.

And last but not least, does this library require/combine with the Phoenix version (in your repositories) - or does it depend on, can it be combined with the regular wxWidgets framework for Python?

Anyhow also big thanks for all the work and taking time reading this inquiry.

**Comment by Metallicow** [comment]
@jrie 

1. The animation demo.(The file itself) provides 3 different ways to use the demo whether you use threads or multiple widgets. The results of the pos move could be recorded,with an added print statement to the file.

2. Absolute positioning or with sizers is possible.

3. Until wxWidgets provides support for touch devices..., then no atm.

4. some require Project Phoenix, some don't. I haven't uploaded any Classic code tho yet. What are you looking for?

**Comment by jrie** [comment]
@Metallicow 
About the points:
1. I was wondering what "animation" in that sense would mean, moving a window or animating a window splitter - animating properties or something related to that/along that lines?
2. Absolute positioning is already very useful, in my case also - after creation of the button itself, can it be repositioned?
3. Well, touch in that sense, that there is a screen having the touch ability, but the touch operating a only mouse - for example like its the case with a Microsoft Surface tablet running Windows 8 or 10 and other touch screens operating only a mouse curser. No special "touch" or gesture threatment.
4. What Im looking for? - I was wondering if MCOW depends on Project Phoenix in particular - which might not be bad in any way - I havent compared Project Phoenix to the "regular" wxWidgets version, just wondering if the features of MCOW do have special requirements, which one might need to take into account when trying to use the library/extension.

Edit: Just to mention, related to 4. - its also about to get rid of Flash....

**Comment by Metallicow** [comment]
1. (Animating the)Moving of a window for the animation.py file and animating a splitter for threewaysplitter.py(also has a mouse gesture mixin)

2. Yes, I wouldn't see why not. SetPosition() or Move() should work fine.

3. I'm not sure what type of dragging you are looking for... DragImage class does this. Most windows can be coded to be draggable(See the demo for example ShapedWindow has code for this), so yes for ShapedBitmapButton.

4. No special requirements. Just wxPython. You would need to tweak a few things in the code to run some of them on Classic wxPython. There is no wxWidgets C code yet(someone could port it :)).
